services:
 #front:
 #  build: ./front/agri-ai-front
 #   container_name: agri-ai-frontend
 #   restart: unless-stopped
 #   ports:
 #     - "3000:3000"
 #   depends_on:
 #     - api
 #   networks:
 #     - agri-ai-network
  api:
    build: ./back
    container_name: agri-ai-api
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - agri-ai-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14
    container_name: agri-ai-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-agriai}
      POSTGRES_PASSWORD: ${POSTGRES_PSW:-agriai123}
      POSTGRES_DB: ${POSTGRES_DB:-agriai}
    networks:
      - agri-ai-network

volumes:
  postgres-data:

networks:
  agri-ai-network:
    driver: bridge
